import Head from 'next/head';
import styled from 'styled-components';
import About from './components/About';
export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Main>
				<H1>Nextjs boilerplate with JavaScript and styled-components!</H1>
				<About />
			</Main>
		</div>
	);
}

const Main = styled.main`
	max-width: 70rem;
	margin: 0 auto;
`;

const H1 = styled.h1`
	font-size: 2rem;
	color: ${props => props.theme.colors.secondary};
	margin-top: 1rem;
`;
